// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DB.proto

package org.example.vcdb.proto;

public final class DB {
  private DB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface createRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DB.createRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dBName = 1;</code>
     * @return The dBName.
     */
    java.lang.String getDBName();
    /**
     * <code>string dBName = 1;</code>
     * @return The bytes for dBName.
     */
    com.google.protobuf.ByteString
        getDBNameBytes();
  }
  /**
   * Protobuf type {@code DB.createRequest}
   */
  public static final class createRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DB.createRequest)
      createRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use createRequest.newBuilder() to construct.
    private createRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private createRequest() {
      dBName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new createRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private createRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              dBName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.vcdb.proto.DB.internal_static_DB_createRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.vcdb.proto.DB.internal_static_DB_createRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.vcdb.proto.DB.createRequest.class, org.example.vcdb.proto.DB.createRequest.Builder.class);
    }

    public static final int DBNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object dBName_;
    /**
     * <code>string dBName = 1;</code>
     * @return The dBName.
     */
    @java.lang.Override
    public java.lang.String getDBName() {
      java.lang.Object ref = dBName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dBName_ = s;
        return s;
      }
    }
    /**
     * <code>string dBName = 1;</code>
     * @return The bytes for dBName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDBNameBytes() {
      java.lang.Object ref = dBName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dBName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDBNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dBName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDBNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dBName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.vcdb.proto.DB.createRequest)) {
        return super.equals(obj);
      }
      org.example.vcdb.proto.DB.createRequest other = (org.example.vcdb.proto.DB.createRequest) obj;

      if (!getDBName()
          .equals(other.getDBName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DBNAME_FIELD_NUMBER;
      hash = (53 * hash) + getDBName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.vcdb.proto.DB.createRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.DB.createRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.createRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.DB.createRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.createRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.DB.createRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.createRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.DB.createRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.createRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.DB.createRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.createRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.DB.createRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.vcdb.proto.DB.createRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DB.createRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DB.createRequest)
        org.example.vcdb.proto.DB.createRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.vcdb.proto.DB.internal_static_DB_createRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.vcdb.proto.DB.internal_static_DB_createRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.vcdb.proto.DB.createRequest.class, org.example.vcdb.proto.DB.createRequest.Builder.class);
      }

      // Construct using org.example.vcdb.proto.DB.createRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dBName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.vcdb.proto.DB.internal_static_DB_createRequest_descriptor;
      }

      @java.lang.Override
      public org.example.vcdb.proto.DB.createRequest getDefaultInstanceForType() {
        return org.example.vcdb.proto.DB.createRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.vcdb.proto.DB.createRequest build() {
        org.example.vcdb.proto.DB.createRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.vcdb.proto.DB.createRequest buildPartial() {
        org.example.vcdb.proto.DB.createRequest result = new org.example.vcdb.proto.DB.createRequest(this);
        result.dBName_ = dBName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.vcdb.proto.DB.createRequest) {
          return mergeFrom((org.example.vcdb.proto.DB.createRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.vcdb.proto.DB.createRequest other) {
        if (other == org.example.vcdb.proto.DB.createRequest.getDefaultInstance()) return this;
        if (!other.getDBName().isEmpty()) {
          dBName_ = other.dBName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.vcdb.proto.DB.createRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.vcdb.proto.DB.createRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object dBName_ = "";
      /**
       * <code>string dBName = 1;</code>
       * @return The dBName.
       */
      public java.lang.String getDBName() {
        java.lang.Object ref = dBName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dBName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dBName = 1;</code>
       * @return The bytes for dBName.
       */
      public com.google.protobuf.ByteString
          getDBNameBytes() {
        java.lang.Object ref = dBName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dBName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dBName = 1;</code>
       * @param value The dBName to set.
       * @return This builder for chaining.
       */
      public Builder setDBName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dBName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dBName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDBName() {
        
        dBName_ = getDefaultInstance().getDBName();
        onChanged();
        return this;
      }
      /**
       * <code>string dBName = 1;</code>
       * @param value The bytes for dBName to set.
       * @return This builder for chaining.
       */
      public Builder setDBNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dBName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DB.createRequest)
    }

    // @@protoc_insertion_point(class_scope:DB.createRequest)
    private static final org.example.vcdb.proto.DB.createRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.vcdb.proto.DB.createRequest();
    }

    public static org.example.vcdb.proto.DB.createRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<createRequest>
        PARSER = new com.google.protobuf.AbstractParser<createRequest>() {
      @java.lang.Override
      public createRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new createRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<createRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<createRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.vcdb.proto.DB.createRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface deleteRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DB.deleteRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dBName = 10;</code>
     * @return The dBName.
     */
    java.lang.String getDBName();
    /**
     * <code>string dBName = 10;</code>
     * @return The bytes for dBName.
     */
    com.google.protobuf.ByteString
        getDBNameBytes();

    /**
     * <code>.DB.DeleteCells deleteCells = 20;</code>
     * @return Whether the deleteCells field is set.
     */
    boolean hasDeleteCells();
    /**
     * <code>.DB.DeleteCells deleteCells = 20;</code>
     * @return The deleteCells.
     */
    org.example.vcdb.proto.DB.DeleteCells getDeleteCells();
    /**
     * <code>.DB.DeleteCells deleteCells = 20;</code>
     */
    org.example.vcdb.proto.DB.DeleteCellsOrBuilder getDeleteCellsOrBuilder();
  }
  /**
   * Protobuf type {@code DB.deleteRequest}
   */
  public static final class deleteRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DB.deleteRequest)
      deleteRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use deleteRequest.newBuilder() to construct.
    private deleteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private deleteRequest() {
      dBName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new deleteRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private deleteRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              dBName_ = s;
              break;
            }
            case 162: {
              org.example.vcdb.proto.DB.DeleteCells.Builder subBuilder = null;
              if (deleteCells_ != null) {
                subBuilder = deleteCells_.toBuilder();
              }
              deleteCells_ = input.readMessage(org.example.vcdb.proto.DB.DeleteCells.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deleteCells_);
                deleteCells_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.vcdb.proto.DB.internal_static_DB_deleteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.vcdb.proto.DB.internal_static_DB_deleteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.vcdb.proto.DB.deleteRequest.class, org.example.vcdb.proto.DB.deleteRequest.Builder.class);
    }

    public static final int DBNAME_FIELD_NUMBER = 10;
    private volatile java.lang.Object dBName_;
    /**
     * <code>string dBName = 10;</code>
     * @return The dBName.
     */
    @java.lang.Override
    public java.lang.String getDBName() {
      java.lang.Object ref = dBName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dBName_ = s;
        return s;
      }
    }
    /**
     * <code>string dBName = 10;</code>
     * @return The bytes for dBName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDBNameBytes() {
      java.lang.Object ref = dBName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dBName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELETECELLS_FIELD_NUMBER = 20;
    private org.example.vcdb.proto.DB.DeleteCells deleteCells_;
    /**
     * <code>.DB.DeleteCells deleteCells = 20;</code>
     * @return Whether the deleteCells field is set.
     */
    @java.lang.Override
    public boolean hasDeleteCells() {
      return deleteCells_ != null;
    }
    /**
     * <code>.DB.DeleteCells deleteCells = 20;</code>
     * @return The deleteCells.
     */
    @java.lang.Override
    public org.example.vcdb.proto.DB.DeleteCells getDeleteCells() {
      return deleteCells_ == null ? org.example.vcdb.proto.DB.DeleteCells.getDefaultInstance() : deleteCells_;
    }
    /**
     * <code>.DB.DeleteCells deleteCells = 20;</code>
     */
    @java.lang.Override
    public org.example.vcdb.proto.DB.DeleteCellsOrBuilder getDeleteCellsOrBuilder() {
      return getDeleteCells();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDBNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, dBName_);
      }
      if (deleteCells_ != null) {
        output.writeMessage(20, getDeleteCells());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDBNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, dBName_);
      }
      if (deleteCells_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(20, getDeleteCells());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.vcdb.proto.DB.deleteRequest)) {
        return super.equals(obj);
      }
      org.example.vcdb.proto.DB.deleteRequest other = (org.example.vcdb.proto.DB.deleteRequest) obj;

      if (!getDBName()
          .equals(other.getDBName())) return false;
      if (hasDeleteCells() != other.hasDeleteCells()) return false;
      if (hasDeleteCells()) {
        if (!getDeleteCells()
            .equals(other.getDeleteCells())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DBNAME_FIELD_NUMBER;
      hash = (53 * hash) + getDBName().hashCode();
      if (hasDeleteCells()) {
        hash = (37 * hash) + DELETECELLS_FIELD_NUMBER;
        hash = (53 * hash) + getDeleteCells().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.vcdb.proto.DB.deleteRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.DB.deleteRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.deleteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.DB.deleteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.deleteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.DB.deleteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.deleteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.DB.deleteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.deleteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.DB.deleteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.deleteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.DB.deleteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.vcdb.proto.DB.deleteRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DB.deleteRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DB.deleteRequest)
        org.example.vcdb.proto.DB.deleteRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.vcdb.proto.DB.internal_static_DB_deleteRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.vcdb.proto.DB.internal_static_DB_deleteRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.vcdb.proto.DB.deleteRequest.class, org.example.vcdb.proto.DB.deleteRequest.Builder.class);
      }

      // Construct using org.example.vcdb.proto.DB.deleteRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dBName_ = "";

        if (deleteCellsBuilder_ == null) {
          deleteCells_ = null;
        } else {
          deleteCells_ = null;
          deleteCellsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.vcdb.proto.DB.internal_static_DB_deleteRequest_descriptor;
      }

      @java.lang.Override
      public org.example.vcdb.proto.DB.deleteRequest getDefaultInstanceForType() {
        return org.example.vcdb.proto.DB.deleteRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.vcdb.proto.DB.deleteRequest build() {
        org.example.vcdb.proto.DB.deleteRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.vcdb.proto.DB.deleteRequest buildPartial() {
        org.example.vcdb.proto.DB.deleteRequest result = new org.example.vcdb.proto.DB.deleteRequest(this);
        result.dBName_ = dBName_;
        if (deleteCellsBuilder_ == null) {
          result.deleteCells_ = deleteCells_;
        } else {
          result.deleteCells_ = deleteCellsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.vcdb.proto.DB.deleteRequest) {
          return mergeFrom((org.example.vcdb.proto.DB.deleteRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.vcdb.proto.DB.deleteRequest other) {
        if (other == org.example.vcdb.proto.DB.deleteRequest.getDefaultInstance()) return this;
        if (!other.getDBName().isEmpty()) {
          dBName_ = other.dBName_;
          onChanged();
        }
        if (other.hasDeleteCells()) {
          mergeDeleteCells(other.getDeleteCells());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.vcdb.proto.DB.deleteRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.vcdb.proto.DB.deleteRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object dBName_ = "";
      /**
       * <code>string dBName = 10;</code>
       * @return The dBName.
       */
      public java.lang.String getDBName() {
        java.lang.Object ref = dBName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dBName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dBName = 10;</code>
       * @return The bytes for dBName.
       */
      public com.google.protobuf.ByteString
          getDBNameBytes() {
        java.lang.Object ref = dBName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dBName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dBName = 10;</code>
       * @param value The dBName to set.
       * @return This builder for chaining.
       */
      public Builder setDBName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dBName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dBName = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearDBName() {
        
        dBName_ = getDefaultInstance().getDBName();
        onChanged();
        return this;
      }
      /**
       * <code>string dBName = 10;</code>
       * @param value The bytes for dBName to set.
       * @return This builder for chaining.
       */
      public Builder setDBNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dBName_ = value;
        onChanged();
        return this;
      }

      private org.example.vcdb.proto.DB.DeleteCells deleteCells_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.example.vcdb.proto.DB.DeleteCells, org.example.vcdb.proto.DB.DeleteCells.Builder, org.example.vcdb.proto.DB.DeleteCellsOrBuilder> deleteCellsBuilder_;
      /**
       * <code>.DB.DeleteCells deleteCells = 20;</code>
       * @return Whether the deleteCells field is set.
       */
      public boolean hasDeleteCells() {
        return deleteCellsBuilder_ != null || deleteCells_ != null;
      }
      /**
       * <code>.DB.DeleteCells deleteCells = 20;</code>
       * @return The deleteCells.
       */
      public org.example.vcdb.proto.DB.DeleteCells getDeleteCells() {
        if (deleteCellsBuilder_ == null) {
          return deleteCells_ == null ? org.example.vcdb.proto.DB.DeleteCells.getDefaultInstance() : deleteCells_;
        } else {
          return deleteCellsBuilder_.getMessage();
        }
      }
      /**
       * <code>.DB.DeleteCells deleteCells = 20;</code>
       */
      public Builder setDeleteCells(org.example.vcdb.proto.DB.DeleteCells value) {
        if (deleteCellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deleteCells_ = value;
          onChanged();
        } else {
          deleteCellsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.DB.DeleteCells deleteCells = 20;</code>
       */
      public Builder setDeleteCells(
          org.example.vcdb.proto.DB.DeleteCells.Builder builderForValue) {
        if (deleteCellsBuilder_ == null) {
          deleteCells_ = builderForValue.build();
          onChanged();
        } else {
          deleteCellsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.DB.DeleteCells deleteCells = 20;</code>
       */
      public Builder mergeDeleteCells(org.example.vcdb.proto.DB.DeleteCells value) {
        if (deleteCellsBuilder_ == null) {
          if (deleteCells_ != null) {
            deleteCells_ =
              org.example.vcdb.proto.DB.DeleteCells.newBuilder(deleteCells_).mergeFrom(value).buildPartial();
          } else {
            deleteCells_ = value;
          }
          onChanged();
        } else {
          deleteCellsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.DB.DeleteCells deleteCells = 20;</code>
       */
      public Builder clearDeleteCells() {
        if (deleteCellsBuilder_ == null) {
          deleteCells_ = null;
          onChanged();
        } else {
          deleteCells_ = null;
          deleteCellsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.DB.DeleteCells deleteCells = 20;</code>
       */
      public org.example.vcdb.proto.DB.DeleteCells.Builder getDeleteCellsBuilder() {
        
        onChanged();
        return getDeleteCellsFieldBuilder().getBuilder();
      }
      /**
       * <code>.DB.DeleteCells deleteCells = 20;</code>
       */
      public org.example.vcdb.proto.DB.DeleteCellsOrBuilder getDeleteCellsOrBuilder() {
        if (deleteCellsBuilder_ != null) {
          return deleteCellsBuilder_.getMessageOrBuilder();
        } else {
          return deleteCells_ == null ?
              org.example.vcdb.proto.DB.DeleteCells.getDefaultInstance() : deleteCells_;
        }
      }
      /**
       * <code>.DB.DeleteCells deleteCells = 20;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.example.vcdb.proto.DB.DeleteCells, org.example.vcdb.proto.DB.DeleteCells.Builder, org.example.vcdb.proto.DB.DeleteCellsOrBuilder> 
          getDeleteCellsFieldBuilder() {
        if (deleteCellsBuilder_ == null) {
          deleteCellsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.example.vcdb.proto.DB.DeleteCells, org.example.vcdb.proto.DB.DeleteCells.Builder, org.example.vcdb.proto.DB.DeleteCellsOrBuilder>(
                  getDeleteCells(),
                  getParentForChildren(),
                  isClean());
          deleteCells_ = null;
        }
        return deleteCellsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DB.deleteRequest)
    }

    // @@protoc_insertion_point(class_scope:DB.deleteRequest)
    private static final org.example.vcdb.proto.DB.deleteRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.vcdb.proto.DB.deleteRequest();
    }

    public static org.example.vcdb.proto.DB.deleteRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<deleteRequest>
        PARSER = new com.google.protobuf.AbstractParser<deleteRequest>() {
      @java.lang.Override
      public deleteRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new deleteRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<deleteRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<deleteRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.vcdb.proto.DB.deleteRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DeleteCellsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DB.DeleteCells)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes cf_names = 10;</code>
     * @return The cfNames.
     */
    com.google.protobuf.ByteString getCfNames();

    /**
     * <code>bytes terms = 20;</code>
     * @return The terms.
     */
    com.google.protobuf.ByteString getTerms();
  }
  /**
   * Protobuf type {@code DB.DeleteCells}
   */
  public static final class DeleteCells extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DB.DeleteCells)
      DeleteCellsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeleteCells.newBuilder() to construct.
    private DeleteCells(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeleteCells() {
      cfNames_ = com.google.protobuf.ByteString.EMPTY;
      terms_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeleteCells();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeleteCells(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 82: {

              cfNames_ = input.readBytes();
              break;
            }
            case 162: {

              terms_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.vcdb.proto.DB.internal_static_DB_DeleteCells_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.vcdb.proto.DB.internal_static_DB_DeleteCells_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.vcdb.proto.DB.DeleteCells.class, org.example.vcdb.proto.DB.DeleteCells.Builder.class);
    }

    public static final int CF_NAMES_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString cfNames_;
    /**
     * <code>bytes cf_names = 10;</code>
     * @return The cfNames.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCfNames() {
      return cfNames_;
    }

    public static final int TERMS_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString terms_;
    /**
     * <code>bytes terms = 20;</code>
     * @return The terms.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTerms() {
      return terms_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!cfNames_.isEmpty()) {
        output.writeBytes(10, cfNames_);
      }
      if (!terms_.isEmpty()) {
        output.writeBytes(20, terms_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!cfNames_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, cfNames_);
      }
      if (!terms_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, terms_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.vcdb.proto.DB.DeleteCells)) {
        return super.equals(obj);
      }
      org.example.vcdb.proto.DB.DeleteCells other = (org.example.vcdb.proto.DB.DeleteCells) obj;

      if (!getCfNames()
          .equals(other.getCfNames())) return false;
      if (!getTerms()
          .equals(other.getTerms())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CF_NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getCfNames().hashCode();
      hash = (37 * hash) + TERMS_FIELD_NUMBER;
      hash = (53 * hash) + getTerms().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.vcdb.proto.DB.DeleteCells parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.DB.DeleteCells parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.DeleteCells parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.DB.DeleteCells parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.DeleteCells parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.DB.DeleteCells parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.DeleteCells parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.DB.DeleteCells parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.DeleteCells parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.DB.DeleteCells parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.DB.DeleteCells parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.DB.DeleteCells parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.vcdb.proto.DB.DeleteCells prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DB.DeleteCells}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DB.DeleteCells)
        org.example.vcdb.proto.DB.DeleteCellsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.vcdb.proto.DB.internal_static_DB_DeleteCells_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.vcdb.proto.DB.internal_static_DB_DeleteCells_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.vcdb.proto.DB.DeleteCells.class, org.example.vcdb.proto.DB.DeleteCells.Builder.class);
      }

      // Construct using org.example.vcdb.proto.DB.DeleteCells.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cfNames_ = com.google.protobuf.ByteString.EMPTY;

        terms_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.vcdb.proto.DB.internal_static_DB_DeleteCells_descriptor;
      }

      @java.lang.Override
      public org.example.vcdb.proto.DB.DeleteCells getDefaultInstanceForType() {
        return org.example.vcdb.proto.DB.DeleteCells.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.vcdb.proto.DB.DeleteCells build() {
        org.example.vcdb.proto.DB.DeleteCells result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.vcdb.proto.DB.DeleteCells buildPartial() {
        org.example.vcdb.proto.DB.DeleteCells result = new org.example.vcdb.proto.DB.DeleteCells(this);
        result.cfNames_ = cfNames_;
        result.terms_ = terms_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.vcdb.proto.DB.DeleteCells) {
          return mergeFrom((org.example.vcdb.proto.DB.DeleteCells)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.vcdb.proto.DB.DeleteCells other) {
        if (other == org.example.vcdb.proto.DB.DeleteCells.getDefaultInstance()) return this;
        if (other.getCfNames() != com.google.protobuf.ByteString.EMPTY) {
          setCfNames(other.getCfNames());
        }
        if (other.getTerms() != com.google.protobuf.ByteString.EMPTY) {
          setTerms(other.getTerms());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.vcdb.proto.DB.DeleteCells parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.vcdb.proto.DB.DeleteCells) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString cfNames_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes cf_names = 10;</code>
       * @return The cfNames.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCfNames() {
        return cfNames_;
      }
      /**
       * <code>bytes cf_names = 10;</code>
       * @param value The cfNames to set.
       * @return This builder for chaining.
       */
      public Builder setCfNames(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cfNames_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes cf_names = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearCfNames() {
        
        cfNames_ = getDefaultInstance().getCfNames();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString terms_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes terms = 20;</code>
       * @return The terms.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTerms() {
        return terms_;
      }
      /**
       * <code>bytes terms = 20;</code>
       * @param value The terms to set.
       * @return This builder for chaining.
       */
      public Builder setTerms(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        terms_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes terms = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerms() {
        
        terms_ = getDefaultInstance().getTerms();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DB.DeleteCells)
    }

    // @@protoc_insertion_point(class_scope:DB.DeleteCells)
    private static final org.example.vcdb.proto.DB.DeleteCells DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.vcdb.proto.DB.DeleteCells();
    }

    public static org.example.vcdb.proto.DB.DeleteCells getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeleteCells>
        PARSER = new com.google.protobuf.AbstractParser<DeleteCells>() {
      @java.lang.Override
      public DeleteCells parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeleteCells(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeleteCells> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeleteCells> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.vcdb.proto.DB.DeleteCells getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_createRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_createRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_deleteRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_deleteRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_DeleteCells_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_DeleteCells_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010DB.proto\022\002DB\032\rVersion.proto\"\037\n\rcreateR" +
      "equest\022\016\n\006dBName\030\001 \001(\t\"E\n\rdeleteRequest\022" +
      "\016\n\006dBName\030\n \001(\t\022$\n\013deleteCells\030\024 \001(\0132\017.D" +
      "B.DeleteCells\".\n\013DeleteCells\022\020\n\010cf_names" +
      "\030\n \001(\014\022\r\n\005terms\030\024 \001(\0142s\n\tdbService\0222\n\010cr" +
      "eateDB\022\021.DB.createRequest\032\021.Version.intR" +
      "eply\"\000\0222\n\010deleteDB\022\021.DB.deleteRequest\032\021." +
      "Version.intReply\"\000B\036\n\026org.example.vcdb.p" +
      "rotoB\002DBP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.example.vcdb.proto.Version.getDescriptor(),
        });
    internal_static_DB_createRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DB_createRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_createRequest_descriptor,
        new java.lang.String[] { "DBName", });
    internal_static_DB_deleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DB_deleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_deleteRequest_descriptor,
        new java.lang.String[] { "DBName", "DeleteCells", });
    internal_static_DB_DeleteCells_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DB_DeleteCells_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_DeleteCells_descriptor,
        new java.lang.String[] { "CfNames", "Terms", });
    org.example.vcdb.proto.Version.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
