// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Table.proto

package org.example.vcdb.proto;

public final class Table {
  private Table() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface createRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Table.createRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dBName = 10;</code>
     * @return The dBName.
     */
    java.lang.String getDBName();
    /**
     * <code>string dBName = 10;</code>
     * @return The bytes for dBName.
     */
    com.google.protobuf.ByteString
        getDBNameBytes();

    /**
     * <code>string tabName = 20;</code>
     * @return The tabName.
     */
    java.lang.String getTabName();
    /**
     * <code>string tabName = 20;</code>
     * @return The bytes for tabName.
     */
    com.google.protobuf.ByteString
        getTabNameBytes();

    /**
     * <code>bytes column_family = 30;</code>
     * @return The columnFamily.
     */
    com.google.protobuf.ByteString getColumnFamily();
  }
  /**
   * Protobuf type {@code Table.createRequest}
   */
  public static final class createRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Table.createRequest)
      createRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use createRequest.newBuilder() to construct.
    private createRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private createRequest() {
      dBName_ = "";
      tabName_ = "";
      columnFamily_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new createRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private createRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              dBName_ = s;
              break;
            }
            case 162: {
              java.lang.String s = input.readStringRequireUtf8();

              tabName_ = s;
              break;
            }
            case 242: {

              columnFamily_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.vcdb.proto.Table.internal_static_Table_createRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.vcdb.proto.Table.internal_static_Table_createRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.vcdb.proto.Table.createRequest.class, org.example.vcdb.proto.Table.createRequest.Builder.class);
    }

    public static final int DBNAME_FIELD_NUMBER = 10;
    private volatile java.lang.Object dBName_;
    /**
     * <code>string dBName = 10;</code>
     * @return The dBName.
     */
    @java.lang.Override
    public java.lang.String getDBName() {
      java.lang.Object ref = dBName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dBName_ = s;
        return s;
      }
    }
    /**
     * <code>string dBName = 10;</code>
     * @return The bytes for dBName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDBNameBytes() {
      java.lang.Object ref = dBName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dBName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABNAME_FIELD_NUMBER = 20;
    private volatile java.lang.Object tabName_;
    /**
     * <code>string tabName = 20;</code>
     * @return The tabName.
     */
    @java.lang.Override
    public java.lang.String getTabName() {
      java.lang.Object ref = tabName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tabName_ = s;
        return s;
      }
    }
    /**
     * <code>string tabName = 20;</code>
     * @return The bytes for tabName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTabNameBytes() {
      java.lang.Object ref = tabName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tabName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMN_FAMILY_FIELD_NUMBER = 30;
    private com.google.protobuf.ByteString columnFamily_;
    /**
     * <code>bytes column_family = 30;</code>
     * @return The columnFamily.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getColumnFamily() {
      return columnFamily_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDBNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, dBName_);
      }
      if (!getTabNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 20, tabName_);
      }
      if (!columnFamily_.isEmpty()) {
        output.writeBytes(30, columnFamily_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDBNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, dBName_);
      }
      if (!getTabNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, tabName_);
      }
      if (!columnFamily_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(30, columnFamily_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.vcdb.proto.Table.createRequest)) {
        return super.equals(obj);
      }
      org.example.vcdb.proto.Table.createRequest other = (org.example.vcdb.proto.Table.createRequest) obj;

      if (!getDBName()
          .equals(other.getDBName())) return false;
      if (!getTabName()
          .equals(other.getTabName())) return false;
      if (!getColumnFamily()
          .equals(other.getColumnFamily())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DBNAME_FIELD_NUMBER;
      hash = (53 * hash) + getDBName().hashCode();
      hash = (37 * hash) + TABNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTabName().hashCode();
      hash = (37 * hash) + COLUMN_FAMILY_FIELD_NUMBER;
      hash = (53 * hash) + getColumnFamily().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.vcdb.proto.Table.createRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.Table.createRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.createRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.Table.createRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.createRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.Table.createRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.createRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.Table.createRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.createRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.Table.createRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.createRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.Table.createRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.vcdb.proto.Table.createRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Table.createRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Table.createRequest)
        org.example.vcdb.proto.Table.createRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.vcdb.proto.Table.internal_static_Table_createRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.vcdb.proto.Table.internal_static_Table_createRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.vcdb.proto.Table.createRequest.class, org.example.vcdb.proto.Table.createRequest.Builder.class);
      }

      // Construct using org.example.vcdb.proto.Table.createRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dBName_ = "";

        tabName_ = "";

        columnFamily_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.vcdb.proto.Table.internal_static_Table_createRequest_descriptor;
      }

      @java.lang.Override
      public org.example.vcdb.proto.Table.createRequest getDefaultInstanceForType() {
        return org.example.vcdb.proto.Table.createRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.vcdb.proto.Table.createRequest build() {
        org.example.vcdb.proto.Table.createRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.vcdb.proto.Table.createRequest buildPartial() {
        org.example.vcdb.proto.Table.createRequest result = new org.example.vcdb.proto.Table.createRequest(this);
        result.dBName_ = dBName_;
        result.tabName_ = tabName_;
        result.columnFamily_ = columnFamily_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.vcdb.proto.Table.createRequest) {
          return mergeFrom((org.example.vcdb.proto.Table.createRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.vcdb.proto.Table.createRequest other) {
        if (other == org.example.vcdb.proto.Table.createRequest.getDefaultInstance()) return this;
        if (!other.getDBName().isEmpty()) {
          dBName_ = other.dBName_;
          onChanged();
        }
        if (!other.getTabName().isEmpty()) {
          tabName_ = other.tabName_;
          onChanged();
        }
        if (other.getColumnFamily() != com.google.protobuf.ByteString.EMPTY) {
          setColumnFamily(other.getColumnFamily());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.vcdb.proto.Table.createRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.vcdb.proto.Table.createRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object dBName_ = "";
      /**
       * <code>string dBName = 10;</code>
       * @return The dBName.
       */
      public java.lang.String getDBName() {
        java.lang.Object ref = dBName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dBName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dBName = 10;</code>
       * @return The bytes for dBName.
       */
      public com.google.protobuf.ByteString
          getDBNameBytes() {
        java.lang.Object ref = dBName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dBName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dBName = 10;</code>
       * @param value The dBName to set.
       * @return This builder for chaining.
       */
      public Builder setDBName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dBName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dBName = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearDBName() {
        
        dBName_ = getDefaultInstance().getDBName();
        onChanged();
        return this;
      }
      /**
       * <code>string dBName = 10;</code>
       * @param value The bytes for dBName to set.
       * @return This builder for chaining.
       */
      public Builder setDBNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dBName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tabName_ = "";
      /**
       * <code>string tabName = 20;</code>
       * @return The tabName.
       */
      public java.lang.String getTabName() {
        java.lang.Object ref = tabName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tabName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tabName = 20;</code>
       * @return The bytes for tabName.
       */
      public com.google.protobuf.ByteString
          getTabNameBytes() {
        java.lang.Object ref = tabName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tabName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tabName = 20;</code>
       * @param value The tabName to set.
       * @return This builder for chaining.
       */
      public Builder setTabName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tabName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tabName = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearTabName() {
        
        tabName_ = getDefaultInstance().getTabName();
        onChanged();
        return this;
      }
      /**
       * <code>string tabName = 20;</code>
       * @param value The bytes for tabName to set.
       * @return This builder for chaining.
       */
      public Builder setTabNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tabName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString columnFamily_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes column_family = 30;</code>
       * @return The columnFamily.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getColumnFamily() {
        return columnFamily_;
      }
      /**
       * <code>bytes column_family = 30;</code>
       * @param value The columnFamily to set.
       * @return This builder for chaining.
       */
      public Builder setColumnFamily(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        columnFamily_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes column_family = 30;</code>
       * @return This builder for chaining.
       */
      public Builder clearColumnFamily() {
        
        columnFamily_ = getDefaultInstance().getColumnFamily();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Table.createRequest)
    }

    // @@protoc_insertion_point(class_scope:Table.createRequest)
    private static final org.example.vcdb.proto.Table.createRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.vcdb.proto.Table.createRequest();
    }

    public static org.example.vcdb.proto.Table.createRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<createRequest>
        PARSER = new com.google.protobuf.AbstractParser<createRequest>() {
      @java.lang.Override
      public createRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new createRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<createRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<createRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.vcdb.proto.Table.createRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface alterRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Table.alterRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dBName = 10;</code>
     * @return The dBName.
     */
    java.lang.String getDBName();
    /**
     * <code>string dBName = 10;</code>
     * @return The bytes for dBName.
     */
    com.google.protobuf.ByteString
        getDBNameBytes();

    /**
     * <code>string tabName = 20;</code>
     * @return The tabName.
     */
    java.lang.String getTabName();
    /**
     * <code>string tabName = 20;</code>
     * @return The bytes for tabName.
     */
    com.google.protobuf.ByteString
        getTabNameBytes();

    /**
     * <code>bytes alter_cells = 30;</code>
     * @return The alterCells.
     */
    com.google.protobuf.ByteString getAlterCells();
  }
  /**
   * Protobuf type {@code Table.alterRequest}
   */
  public static final class alterRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Table.alterRequest)
      alterRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use alterRequest.newBuilder() to construct.
    private alterRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private alterRequest() {
      dBName_ = "";
      tabName_ = "";
      alterCells_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new alterRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private alterRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              dBName_ = s;
              break;
            }
            case 162: {
              java.lang.String s = input.readStringRequireUtf8();

              tabName_ = s;
              break;
            }
            case 242: {

              alterCells_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.vcdb.proto.Table.internal_static_Table_alterRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.vcdb.proto.Table.internal_static_Table_alterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.vcdb.proto.Table.alterRequest.class, org.example.vcdb.proto.Table.alterRequest.Builder.class);
    }

    public static final int DBNAME_FIELD_NUMBER = 10;
    private volatile java.lang.Object dBName_;
    /**
     * <code>string dBName = 10;</code>
     * @return The dBName.
     */
    @java.lang.Override
    public java.lang.String getDBName() {
      java.lang.Object ref = dBName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dBName_ = s;
        return s;
      }
    }
    /**
     * <code>string dBName = 10;</code>
     * @return The bytes for dBName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDBNameBytes() {
      java.lang.Object ref = dBName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dBName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABNAME_FIELD_NUMBER = 20;
    private volatile java.lang.Object tabName_;
    /**
     * <code>string tabName = 20;</code>
     * @return The tabName.
     */
    @java.lang.Override
    public java.lang.String getTabName() {
      java.lang.Object ref = tabName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tabName_ = s;
        return s;
      }
    }
    /**
     * <code>string tabName = 20;</code>
     * @return The bytes for tabName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTabNameBytes() {
      java.lang.Object ref = tabName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tabName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALTER_CELLS_FIELD_NUMBER = 30;
    private com.google.protobuf.ByteString alterCells_;
    /**
     * <code>bytes alter_cells = 30;</code>
     * @return The alterCells.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAlterCells() {
      return alterCells_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDBNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, dBName_);
      }
      if (!getTabNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 20, tabName_);
      }
      if (!alterCells_.isEmpty()) {
        output.writeBytes(30, alterCells_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDBNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, dBName_);
      }
      if (!getTabNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, tabName_);
      }
      if (!alterCells_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(30, alterCells_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.vcdb.proto.Table.alterRequest)) {
        return super.equals(obj);
      }
      org.example.vcdb.proto.Table.alterRequest other = (org.example.vcdb.proto.Table.alterRequest) obj;

      if (!getDBName()
          .equals(other.getDBName())) return false;
      if (!getTabName()
          .equals(other.getTabName())) return false;
      if (!getAlterCells()
          .equals(other.getAlterCells())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DBNAME_FIELD_NUMBER;
      hash = (53 * hash) + getDBName().hashCode();
      hash = (37 * hash) + TABNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTabName().hashCode();
      hash = (37 * hash) + ALTER_CELLS_FIELD_NUMBER;
      hash = (53 * hash) + getAlterCells().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.vcdb.proto.Table.alterRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.Table.alterRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.alterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.Table.alterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.alterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.Table.alterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.alterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.Table.alterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.alterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.Table.alterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.alterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.Table.alterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.vcdb.proto.Table.alterRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Table.alterRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Table.alterRequest)
        org.example.vcdb.proto.Table.alterRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.vcdb.proto.Table.internal_static_Table_alterRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.vcdb.proto.Table.internal_static_Table_alterRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.vcdb.proto.Table.alterRequest.class, org.example.vcdb.proto.Table.alterRequest.Builder.class);
      }

      // Construct using org.example.vcdb.proto.Table.alterRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dBName_ = "";

        tabName_ = "";

        alterCells_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.vcdb.proto.Table.internal_static_Table_alterRequest_descriptor;
      }

      @java.lang.Override
      public org.example.vcdb.proto.Table.alterRequest getDefaultInstanceForType() {
        return org.example.vcdb.proto.Table.alterRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.vcdb.proto.Table.alterRequest build() {
        org.example.vcdb.proto.Table.alterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.vcdb.proto.Table.alterRequest buildPartial() {
        org.example.vcdb.proto.Table.alterRequest result = new org.example.vcdb.proto.Table.alterRequest(this);
        result.dBName_ = dBName_;
        result.tabName_ = tabName_;
        result.alterCells_ = alterCells_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.vcdb.proto.Table.alterRequest) {
          return mergeFrom((org.example.vcdb.proto.Table.alterRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.vcdb.proto.Table.alterRequest other) {
        if (other == org.example.vcdb.proto.Table.alterRequest.getDefaultInstance()) return this;
        if (!other.getDBName().isEmpty()) {
          dBName_ = other.dBName_;
          onChanged();
        }
        if (!other.getTabName().isEmpty()) {
          tabName_ = other.tabName_;
          onChanged();
        }
        if (other.getAlterCells() != com.google.protobuf.ByteString.EMPTY) {
          setAlterCells(other.getAlterCells());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.vcdb.proto.Table.alterRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.vcdb.proto.Table.alterRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object dBName_ = "";
      /**
       * <code>string dBName = 10;</code>
       * @return The dBName.
       */
      public java.lang.String getDBName() {
        java.lang.Object ref = dBName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dBName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dBName = 10;</code>
       * @return The bytes for dBName.
       */
      public com.google.protobuf.ByteString
          getDBNameBytes() {
        java.lang.Object ref = dBName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dBName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dBName = 10;</code>
       * @param value The dBName to set.
       * @return This builder for chaining.
       */
      public Builder setDBName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dBName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dBName = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearDBName() {
        
        dBName_ = getDefaultInstance().getDBName();
        onChanged();
        return this;
      }
      /**
       * <code>string dBName = 10;</code>
       * @param value The bytes for dBName to set.
       * @return This builder for chaining.
       */
      public Builder setDBNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dBName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tabName_ = "";
      /**
       * <code>string tabName = 20;</code>
       * @return The tabName.
       */
      public java.lang.String getTabName() {
        java.lang.Object ref = tabName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tabName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tabName = 20;</code>
       * @return The bytes for tabName.
       */
      public com.google.protobuf.ByteString
          getTabNameBytes() {
        java.lang.Object ref = tabName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tabName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tabName = 20;</code>
       * @param value The tabName to set.
       * @return This builder for chaining.
       */
      public Builder setTabName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tabName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tabName = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearTabName() {
        
        tabName_ = getDefaultInstance().getTabName();
        onChanged();
        return this;
      }
      /**
       * <code>string tabName = 20;</code>
       * @param value The bytes for tabName to set.
       * @return This builder for chaining.
       */
      public Builder setTabNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tabName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString alterCells_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes alter_cells = 30;</code>
       * @return The alterCells.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAlterCells() {
        return alterCells_;
      }
      /**
       * <code>bytes alter_cells = 30;</code>
       * @param value The alterCells to set.
       * @return This builder for chaining.
       */
      public Builder setAlterCells(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        alterCells_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes alter_cells = 30;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlterCells() {
        
        alterCells_ = getDefaultInstance().getAlterCells();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Table.alterRequest)
    }

    // @@protoc_insertion_point(class_scope:Table.alterRequest)
    private static final org.example.vcdb.proto.Table.alterRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.vcdb.proto.Table.alterRequest();
    }

    public static org.example.vcdb.proto.Table.alterRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<alterRequest>
        PARSER = new com.google.protobuf.AbstractParser<alterRequest>() {
      @java.lang.Override
      public alterRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new alterRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<alterRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<alterRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.vcdb.proto.Table.alterRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface deleteRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Table.deleteRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dBName = 10;</code>
     * @return The dBName.
     */
    java.lang.String getDBName();
    /**
     * <code>string dBName = 10;</code>
     * @return The bytes for dBName.
     */
    com.google.protobuf.ByteString
        getDBNameBytes();

    /**
     * <code>string tabName = 20;</code>
     * @return The tabName.
     */
    java.lang.String getTabName();
    /**
     * <code>string tabName = 20;</code>
     * @return The bytes for tabName.
     */
    com.google.protobuf.ByteString
        getTabNameBytes();
  }
  /**
   * Protobuf type {@code Table.deleteRequest}
   */
  public static final class deleteRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Table.deleteRequest)
      deleteRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use deleteRequest.newBuilder() to construct.
    private deleteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private deleteRequest() {
      dBName_ = "";
      tabName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new deleteRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private deleteRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              dBName_ = s;
              break;
            }
            case 162: {
              java.lang.String s = input.readStringRequireUtf8();

              tabName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.vcdb.proto.Table.internal_static_Table_deleteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.vcdb.proto.Table.internal_static_Table_deleteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.vcdb.proto.Table.deleteRequest.class, org.example.vcdb.proto.Table.deleteRequest.Builder.class);
    }

    public static final int DBNAME_FIELD_NUMBER = 10;
    private volatile java.lang.Object dBName_;
    /**
     * <code>string dBName = 10;</code>
     * @return The dBName.
     */
    @java.lang.Override
    public java.lang.String getDBName() {
      java.lang.Object ref = dBName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dBName_ = s;
        return s;
      }
    }
    /**
     * <code>string dBName = 10;</code>
     * @return The bytes for dBName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDBNameBytes() {
      java.lang.Object ref = dBName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dBName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABNAME_FIELD_NUMBER = 20;
    private volatile java.lang.Object tabName_;
    /**
     * <code>string tabName = 20;</code>
     * @return The tabName.
     */
    @java.lang.Override
    public java.lang.String getTabName() {
      java.lang.Object ref = tabName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tabName_ = s;
        return s;
      }
    }
    /**
     * <code>string tabName = 20;</code>
     * @return The bytes for tabName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTabNameBytes() {
      java.lang.Object ref = tabName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tabName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDBNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, dBName_);
      }
      if (!getTabNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 20, tabName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDBNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, dBName_);
      }
      if (!getTabNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, tabName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.vcdb.proto.Table.deleteRequest)) {
        return super.equals(obj);
      }
      org.example.vcdb.proto.Table.deleteRequest other = (org.example.vcdb.proto.Table.deleteRequest) obj;

      if (!getDBName()
          .equals(other.getDBName())) return false;
      if (!getTabName()
          .equals(other.getTabName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DBNAME_FIELD_NUMBER;
      hash = (53 * hash) + getDBName().hashCode();
      hash = (37 * hash) + TABNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTabName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.vcdb.proto.Table.deleteRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.Table.deleteRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.deleteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.Table.deleteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.deleteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.Table.deleteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.deleteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.Table.deleteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.deleteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.Table.deleteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.Table.deleteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.Table.deleteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.vcdb.proto.Table.deleteRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Table.deleteRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Table.deleteRequest)
        org.example.vcdb.proto.Table.deleteRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.vcdb.proto.Table.internal_static_Table_deleteRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.vcdb.proto.Table.internal_static_Table_deleteRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.vcdb.proto.Table.deleteRequest.class, org.example.vcdb.proto.Table.deleteRequest.Builder.class);
      }

      // Construct using org.example.vcdb.proto.Table.deleteRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dBName_ = "";

        tabName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.vcdb.proto.Table.internal_static_Table_deleteRequest_descriptor;
      }

      @java.lang.Override
      public org.example.vcdb.proto.Table.deleteRequest getDefaultInstanceForType() {
        return org.example.vcdb.proto.Table.deleteRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.vcdb.proto.Table.deleteRequest build() {
        org.example.vcdb.proto.Table.deleteRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.vcdb.proto.Table.deleteRequest buildPartial() {
        org.example.vcdb.proto.Table.deleteRequest result = new org.example.vcdb.proto.Table.deleteRequest(this);
        result.dBName_ = dBName_;
        result.tabName_ = tabName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.vcdb.proto.Table.deleteRequest) {
          return mergeFrom((org.example.vcdb.proto.Table.deleteRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.vcdb.proto.Table.deleteRequest other) {
        if (other == org.example.vcdb.proto.Table.deleteRequest.getDefaultInstance()) return this;
        if (!other.getDBName().isEmpty()) {
          dBName_ = other.dBName_;
          onChanged();
        }
        if (!other.getTabName().isEmpty()) {
          tabName_ = other.tabName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.vcdb.proto.Table.deleteRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.vcdb.proto.Table.deleteRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object dBName_ = "";
      /**
       * <code>string dBName = 10;</code>
       * @return The dBName.
       */
      public java.lang.String getDBName() {
        java.lang.Object ref = dBName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dBName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dBName = 10;</code>
       * @return The bytes for dBName.
       */
      public com.google.protobuf.ByteString
          getDBNameBytes() {
        java.lang.Object ref = dBName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dBName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dBName = 10;</code>
       * @param value The dBName to set.
       * @return This builder for chaining.
       */
      public Builder setDBName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dBName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dBName = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearDBName() {
        
        dBName_ = getDefaultInstance().getDBName();
        onChanged();
        return this;
      }
      /**
       * <code>string dBName = 10;</code>
       * @param value The bytes for dBName to set.
       * @return This builder for chaining.
       */
      public Builder setDBNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dBName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tabName_ = "";
      /**
       * <code>string tabName = 20;</code>
       * @return The tabName.
       */
      public java.lang.String getTabName() {
        java.lang.Object ref = tabName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tabName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tabName = 20;</code>
       * @return The bytes for tabName.
       */
      public com.google.protobuf.ByteString
          getTabNameBytes() {
        java.lang.Object ref = tabName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tabName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tabName = 20;</code>
       * @param value The tabName to set.
       * @return This builder for chaining.
       */
      public Builder setTabName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tabName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tabName = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearTabName() {
        
        tabName_ = getDefaultInstance().getTabName();
        onChanged();
        return this;
      }
      /**
       * <code>string tabName = 20;</code>
       * @param value The bytes for tabName to set.
       * @return This builder for chaining.
       */
      public Builder setTabNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tabName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Table.deleteRequest)
    }

    // @@protoc_insertion_point(class_scope:Table.deleteRequest)
    private static final org.example.vcdb.proto.Table.deleteRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.vcdb.proto.Table.deleteRequest();
    }

    public static org.example.vcdb.proto.Table.deleteRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<deleteRequest>
        PARSER = new com.google.protobuf.AbstractParser<deleteRequest>() {
      @java.lang.Override
      public deleteRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new deleteRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<deleteRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<deleteRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.vcdb.proto.Table.deleteRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Table_createRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Table_createRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Table_alterRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Table_alterRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Table_deleteRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Table_deleteRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Table.proto\022\005Table\032\rVersion.proto\"G\n\rc" +
      "reateRequest\022\016\n\006dBName\030\n \001(\t\022\017\n\007tabName\030" +
      "\024 \001(\t\022\025\n\rcolumn_family\030\036 \001(\014\"D\n\014alterReq" +
      "uest\022\016\n\006dBName\030\n \001(\t\022\017\n\007tabName\030\024 \001(\t\022\023\n" +
      "\013alter_cells\030\036 \001(\014\"0\n\rdeleteRequest\022\016\n\006d" +
      "BName\030\n \001(\t\022\017\n\007tabName\030\024 \001(\t2\272\001\n\014tableSe" +
      "rvice\0228\n\013createTable\022\024.Table.createReque" +
      "st\032\021.Version.intReply\"\000\0226\n\nalterTable\022\023." +
      "Table.alterRequest\032\021.Version.intReply\"\000\022" +
      "8\n\013deleteTable\022\024.Table.deleteRequest\032\021.V" +
      "ersion.intReply\"\000B!\n\026org.example.vcdb.pr" +
      "otoB\005TableP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.example.vcdb.proto.Version.getDescriptor(),
        });
    internal_static_Table_createRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Table_createRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Table_createRequest_descriptor,
        new java.lang.String[] { "DBName", "TabName", "ColumnFamily", });
    internal_static_Table_alterRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Table_alterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Table_alterRequest_descriptor,
        new java.lang.String[] { "DBName", "TabName", "AlterCells", });
    internal_static_Table_deleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Table_deleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Table_deleteRequest_descriptor,
        new java.lang.String[] { "DBName", "TabName", });
    org.example.vcdb.proto.Version.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
