// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transaction.proto

package org.example.vcdb.proto;

public final class Transaction {
  private Transaction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface openTransactionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Transaction.openTransactionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string explainValue = 10;</code>
     * @return The explainValue.
     */
    java.lang.String getExplainValue();
    /**
     * <code>string explainValue = 10;</code>
     * @return The bytes for explainValue.
     */
    com.google.protobuf.ByteString
        getExplainValueBytes();
  }
  /**
   * Protobuf type {@code Transaction.openTransactionRequest}
   */
  public static final class openTransactionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Transaction.openTransactionRequest)
      openTransactionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use openTransactionRequest.newBuilder() to construct.
    private openTransactionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private openTransactionRequest() {
      explainValue_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new openTransactionRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private openTransactionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              explainValue_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.vcdb.proto.Transaction.internal_static_Transaction_openTransactionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.vcdb.proto.Transaction.internal_static_Transaction_openTransactionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.vcdb.proto.Transaction.openTransactionRequest.class, org.example.vcdb.proto.Transaction.openTransactionRequest.Builder.class);
    }

    public static final int EXPLAINVALUE_FIELD_NUMBER = 10;
    private volatile java.lang.Object explainValue_;
    /**
     * <code>string explainValue = 10;</code>
     * @return The explainValue.
     */
    @java.lang.Override
    public java.lang.String getExplainValue() {
      java.lang.Object ref = explainValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        explainValue_ = s;
        return s;
      }
    }
    /**
     * <code>string explainValue = 10;</code>
     * @return The bytes for explainValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExplainValueBytes() {
      java.lang.Object ref = explainValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        explainValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getExplainValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, explainValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getExplainValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, explainValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.vcdb.proto.Transaction.openTransactionRequest)) {
        return super.equals(obj);
      }
      org.example.vcdb.proto.Transaction.openTransactionRequest other = (org.example.vcdb.proto.Transaction.openTransactionRequest) obj;

      if (!getExplainValue()
          .equals(other.getExplainValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXPLAINVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getExplainValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.vcdb.proto.Transaction.openTransactionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.Transaction.openTransactionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.Transaction.openTransactionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.Transaction.openTransactionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.Transaction.openTransactionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.vcdb.proto.Transaction.openTransactionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.vcdb.proto.Transaction.openTransactionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.Transaction.openTransactionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.Transaction.openTransactionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.Transaction.openTransactionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.vcdb.proto.Transaction.openTransactionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.vcdb.proto.Transaction.openTransactionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.vcdb.proto.Transaction.openTransactionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Transaction.openTransactionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Transaction.openTransactionRequest)
        org.example.vcdb.proto.Transaction.openTransactionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.vcdb.proto.Transaction.internal_static_Transaction_openTransactionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.vcdb.proto.Transaction.internal_static_Transaction_openTransactionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.vcdb.proto.Transaction.openTransactionRequest.class, org.example.vcdb.proto.Transaction.openTransactionRequest.Builder.class);
      }

      // Construct using org.example.vcdb.proto.Transaction.openTransactionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        explainValue_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.vcdb.proto.Transaction.internal_static_Transaction_openTransactionRequest_descriptor;
      }

      @java.lang.Override
      public org.example.vcdb.proto.Transaction.openTransactionRequest getDefaultInstanceForType() {
        return org.example.vcdb.proto.Transaction.openTransactionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.vcdb.proto.Transaction.openTransactionRequest build() {
        org.example.vcdb.proto.Transaction.openTransactionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.vcdb.proto.Transaction.openTransactionRequest buildPartial() {
        org.example.vcdb.proto.Transaction.openTransactionRequest result = new org.example.vcdb.proto.Transaction.openTransactionRequest(this);
        result.explainValue_ = explainValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.vcdb.proto.Transaction.openTransactionRequest) {
          return mergeFrom((org.example.vcdb.proto.Transaction.openTransactionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.vcdb.proto.Transaction.openTransactionRequest other) {
        if (other == org.example.vcdb.proto.Transaction.openTransactionRequest.getDefaultInstance()) return this;
        if (!other.getExplainValue().isEmpty()) {
          explainValue_ = other.explainValue_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.vcdb.proto.Transaction.openTransactionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.vcdb.proto.Transaction.openTransactionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object explainValue_ = "";
      /**
       * <code>string explainValue = 10;</code>
       * @return The explainValue.
       */
      public java.lang.String getExplainValue() {
        java.lang.Object ref = explainValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          explainValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string explainValue = 10;</code>
       * @return The bytes for explainValue.
       */
      public com.google.protobuf.ByteString
          getExplainValueBytes() {
        java.lang.Object ref = explainValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          explainValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string explainValue = 10;</code>
       * @param value The explainValue to set.
       * @return This builder for chaining.
       */
      public Builder setExplainValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        explainValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string explainValue = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearExplainValue() {
        
        explainValue_ = getDefaultInstance().getExplainValue();
        onChanged();
        return this;
      }
      /**
       * <code>string explainValue = 10;</code>
       * @param value The bytes for explainValue to set.
       * @return This builder for chaining.
       */
      public Builder setExplainValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        explainValue_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Transaction.openTransactionRequest)
    }

    // @@protoc_insertion_point(class_scope:Transaction.openTransactionRequest)
    private static final org.example.vcdb.proto.Transaction.openTransactionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.vcdb.proto.Transaction.openTransactionRequest();
    }

    public static org.example.vcdb.proto.Transaction.openTransactionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<openTransactionRequest>
        PARSER = new com.google.protobuf.AbstractParser<openTransactionRequest>() {
      @java.lang.Override
      public openTransactionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new openTransactionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<openTransactionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<openTransactionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.vcdb.proto.Transaction.openTransactionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Transaction_openTransactionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Transaction_openTransactionRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Transaction.proto\022\013Transaction\032\033google" +
      "/protobuf/empty.proto\032\rVersion.proto\".\n\026" +
      "openTransactionRequest\022\024\n\014explainValue\030\n" +
      " \001(\t2\242\001\n\022transactionService\022K\n\017openTrans" +
      "action\022#.Transaction.openTransactionRequ" +
      "est\032\021.Version.intReply\"\000\022?\n\020closeTransac" +
      "tion\022\026.google.protobuf.Empty\032\021.Version.i" +
      "ntReply\"\000B\'\n\026org.example.vcdb.protoB\013Tra" +
      "nsactionP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          org.example.vcdb.proto.Version.getDescriptor(),
        });
    internal_static_Transaction_openTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Transaction_openTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Transaction_openTransactionRequest_descriptor,
        new java.lang.String[] { "ExplainValue", });
    com.google.protobuf.EmptyProto.getDescriptor();
    org.example.vcdb.proto.Version.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
